---
title: "R Notebook"
output: html_notebook
---

## Chargement des librairies et des données.
```{r}
library(ggplot2)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(randomForest)
source("~/suivi-du-data-camp-DeSantiago_Boulahfa_Akrout/code/projet_fct.R")
```

```{r}
data = read.csv("~/suivi-du-data-camp-DeSantiago_Boulahfa_Akrout/code/data_train.csv")
data=data[,-1]
head(data)
```

```{r}
data=data %>% mutate(sequence = as.factor(sequence)) %>% 
  #mutate(index_sequence = as.factor(index_sequence)) %>% 
  mutate(seq_be = as.factor(seq_be)) %>% 
  mutate(seq_af = as.factor(seq_af)) %>% 
  mutate(sequence = as.factor(sequence)) %>% 
  mutate(structure = as.factor(structure)) %>%
  mutate(struct_be = as.factor(struct_be)) %>% 
  mutate(struct_af = as.factor(struct_af)) %>% 
  mutate(predicted_loop_type = as.factor(predicted_loop_type)) %>% 
  mutate(loop_type_be = as.factor(loop_type_be)) %>% 
  mutate(loop_type_af = as.factor(loop_type_af)) 

data=data[data$SN_filter==1,]
rownames(data)=NULL#1:108052
```

```{r}
tamp=train_test_split(data)
data_train=tamp$train
data_val=tamp$val
```

