---
title: "R Notebook"
output: md_document
---

## Chargement des librairies et des données.
```{r}
library(ggplot2)
library(tidyverse)
source("~/suivi-du-data-camp-DeSantiago_Boulahfa_Akrout/code/projet_fct.R")
```

```{r}
data_filtered = read.csv("~/suivi-du-data-camp-DeSantiago_Boulahfa_Akrout/code/data_filtered.csv")
colnames(data_filtered)[1] <- "Position"
colnames(data_filtered)[2] <- "Covariable"

data_filtered$Covariable = recode_factor(data_filtered$Covariable,"score_structure_boucle"="reactivity")
```

```{r}
noms=colnames(data_filtered)[3:1591]
for (i in noms){
  data_filtered[which(data_filtered[,i]<0),i]=0
}
```

```{r}
nucleotide=extraction_vect(data_filtered,'nucléotide')
loop=extraction_vect(data_filtered,'structure_boucle')
Y_reactivity = extraction_vect(data_filtered,'reactivity')
Y_score_mg_ph10 = extraction_vect(data_filtered,'score_mg_ph10')
Y_score_ph10 = extraction_vect(data_filtered,'score_ph10')
Y_score_mg_50c = extraction_vect(data_filtered,'score_mg_50c')
Y_score_50c = extraction_vect(data_filtered,'score_50c')
```


## Modèles naifs

### LM
```{r}
model=lm(Y_reactivity~as.factor(nucleotide))
summary(model)
```

```{r}
model=lm(Y_reactivity~as.factor(nucleotide)+as.factor(loop))
summary(model)
```

### GLM : loi Gamma

```{r}
model=glm(Y_reactivity+1e-12~as.factor(nucleotide),family = Gamma)
summary(model)
```


```{r}
model=glm(Y_reactivity+1e-12~as.factor(nucleotide)+as.factor(loop),family = Gamma)
summary(model)
```

penser aux relations d'ordre 2 entre les variables !

```{r}
model=glm(Y_reactivity+1e-12~(as.factor(nucleotide)+as.factor(loop))^2,family = Gamma)
summary(model)
```

